import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata = {
  title: "Essenca Wellness Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased`}>
        <header className="sticky top-0 z-50">
          <Navbar />
        </header>
        <main className=" lg:min-h-[calc(100vh-696.5px)]">{children}</main>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
